notification_dashboard/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^dashboard/', include('notifications.urls')),
    url(r'^admin/', admin.site.urls),
]

notifications/urls.py
from django.conf.urls import url

from . import views

app_name = 'notifications'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^notifications/all/$', views.AllNotificationsView.as_view(), name='allnotifications'),
    url(r'^users/$', views.AllUsersView.as_view(), name='users'),
    url(r'^users/(?P<pk>[0-9]+)/$', views.UserDetails.as_view(), name='user_detail'),
    url(r'^notifications/create/$', views.NotificationCreateView.as_view(), name='create'),
    url(r'^notifications/(?P<pk>[0-9]+)/$', views.NotificationDetails.as_view(), name='notification_detail'),
]

notifications/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import mimetypes

from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils import timezone
from django_mysql.models import Model


class User(Model):
    """ User model - contains user attributes"""
    user_name = models.CharField(max_length=200, blank=True, null=True)
    created_time = models.DateTimeField()
    user_city = models.CharField(max_length=200, blank=True, null=True)
    # To track whether user has uninstalled from all devices
    installed = models.BooleanField(default=True)

    def __str__(self):
        return self.user_name


class Device(Model):
    """ Device model - contains device attributes"""
    # Each user can have multiple devices, so map device to user
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_time = models.DateTimeField()
    # Device Push ID, such as Registration ID in Android, Push token in iOS
    push_id = models.CharField(max_length=200)
    # OS platform - Android, iOS etc.
    os = models.CharField(max_length=20)
    # To track whether device has been uninstalled so notification should not be attempted next time
    installed = models.BooleanField(default=True)


def validate_image_url(url):
    """ Validate mime type from image url """
    mime_type, enc = mimetypes.guess_type(url)
    return mime_type and mime_type.startswith('image')


def validate_send_time(send_time):
    """ Validate if send time is greater than current time """
    return send_time > timezone.now()


class NotificationData(Model):
    """ Notification Data model - will store payload, schedule, status, and user properties to which notification
    should be sent """
    notification_name = models.CharField(max_length=50)
    header = models.CharField(max_length=150, validators=[MinLengthValidator(20)])
    content = models.CharField(max_length=300, validators=[MinLengthValidator(20)])
    image_url = models.URLField(validators=[validate_image_url])
    created_time = models.DateTimeField(editable=False)
    send_time = models.DateTimeField(validators=[validate_send_time])
    updated_time = models.DateTimeField()

    # User property using which users can be chosen - for e.g., id, user_name, user_city
    user_property = models.CharField(max_length=50)
    # Values for the selected user property
    user_property_values = models.CharField(max_length=1000)
    # To track whether notification has been sent
    sent_status = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not validate_image_url(self.image_url):
            raise ValidationError('Not a valid image url: MIME type is not image')
        if not validate_send_time(self.send_time):
            raise ValidationError('Scheduled time should be greater than current time')
        if not self.id:
            self.created_time = timezone.now()
        self.updated_time = timezone.now()
        return super(NotificationData, self).save(*args, **kwargs)

notifications/views.py
import datetime

from django.core.exceptions import ValidationError
from django.views import generic
from django.http import HttpResponse
from rest_framework import status
from rest_framework.response import Response
from django.shortcuts import render
from django.views.generic.edit import CreateView
from rest_framework.renderers import TemplateHTMLRenderer

from .models import User, NotificationData
from .serializers import UserSerializer, NotificationDataSerializer
from .tasks import send_notification


def index(request):
    """ Renders index page """
    template_name = 'notifications/index.html'
    return render(request, template_name)


class AllNotificationsView(generic.ListView):
    """ View for all notifications data"""
    template_name = 'notifications/all_notifications.html'
    context_object_name = 'notifications_list'

    def get_queryset(self):
        """ Get all notifications in reverse order of created time"""
        return NotificationData.objects.order_by('-created_time')


class NotificationDetails(generic.DetailView):
    """View for notification details"""
    model = NotificationData
    template_name = 'notifications/notification_detail.html'
    context_object_name = 'notification_data'


class AllUsersView(generic.ListView):
    """ View for all users' data """
    template_name = 'notifications/all_users.html'
    context_object_name = 'users_list'

    def get_queryset(self):
        return User.objects.all()


class UserDetails(generic.DetailView):
    """View for user details"""
    model = User
    template_name = 'notifications/user_detail.html'
    context_object_name = 'user'


class NotificationCreateView(CreateView):
    """ View to schedule a notification"""
    model = NotificationData
    # form_class = 'notifications/notificationdata_form.html'
    fields = ['header', 'content', 'image_url', 'send_time', 'user_property', 'user_property_values',
              'notification_name']
    # renderer_classes = [TemplateHTMLRenderer]

    def post(self, request):
        request_data = request._post
        serializer = NotificationDataSerializer(data=request_data)
        # If data is serialized successfully, return a successful response, else return errors
        try:
            if serializer.is_valid():
                notification_obj = serializer.save()
                send_time = datetime.datetime.strptime(request_data['send_time'], "%Y-%m-%d %H:%M:%S")
                user_property = request_data['user_property']
                user_property_values = request_data['user_property_values']
                payload = {
                    'header': request_data['header'],
                    'content': request_data['content'],
                    'image_url': request_data['image_url']
                }
                send_notification.apply_async(
                    (user_property, user_property_values, payload, notification_obj.id), eta=send_time)
                return HttpResponse("Successfully scheduled notification")
            else:
                return HttpResponse("Errors: " + str(serializer.errors))
        except ValidationError, e:
            return HttpResponse("Error in validating notification data: " + str(e))

notifications/templates/notifications/all_notifications.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/index.css' %}"/>
<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
<link rel="stylesheet" href="{% static 'css/gh-pages.materialize.css' %}">
<!DOCTYPE html>
<html lang="en">
<body>
<div id="circle" class="section scrollspy">
    <div class="row">
        <div class="col s12">
            <h2 class="header">All Notifications</h2><br>
            {% if notifications_list %}
            <ul class="collection">
                {% for notification_data in notifications_list %}
                <li class="collection-item avatar">
                    <img src={{ notification_data.image_url }} alt="" class="circle">
                    <a href="/dashboard/notifications/{{ notification_data.id }}/"> <span class="title">{{ notification_data.notification_name }}</span></a>
                    <p>{{ notification_data.header }}<br>
                        {{ notification_data.content }}
                    </p>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p>No notifications are available.</p>
            {% endif %}
        </div>
    </div>
</div>
</body>
</html>

notifications/templates/notifications/all_users.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/index.css' %}"/>
<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
<link rel="stylesheet" href="{% static 'css/gh-pages.materialize.css' %}">
<!DOCTYPE html>
<html lang="en">
<body>
<div id="circle" class="section scrollspy">
    <div class="row">
        <div class="col s12">
            <h2 class="header">All Users</h2><br>
            {% if users_list %}
            <ul class="collection">
                {% for user in users_list %}
                <li class="collection-item avatar">{{ user.id }}:
                    <a href="/dashboard/users/{{ user.id }}/"> <span class="title">{{ user.user_name }}</span></a>
                    <p>{{ user.city }}
                    </p>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <p>No users are available.</p>
            {% endif %}
        </div>
    </div>
</div>
</body>
</html>

notifications/templates/notifications/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/index.css' %}"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
<link rel="stylesheet" href="{% static 'css/gh-pages.materialize.css' %}">
<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!DOCTYPE html>
<html lang="en">
    <body>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
    <br><br>
    <h2 style="text-align:center;" class="header">Notifications Dashboard</h2>
    <div class="row">
        <div  class="col s4">
            <div class="center promo promo-example">
                <a href='/dashboard/notifications/create'>
                    <i class="material-icons">notifications</i>
                    <p class="promo-caption">Schedule Notification</p>
                </a>
            </div>
        </div>
        <div  class="col s4">
            <div class="center promo promo-example" class="col s4">
                <a href='/dashboard/users'>
                    <i class="material-icons">group</i>
                    <p class="promo-caption">All Users</p>
                </a>
            </div>
        </div>
        <div  class="col s4">
            <div class="center promo promo-example" class="col s4">
                <a href='/dashboard/notifications/all'>
                    <i class="material-icons">speaker_phone</i>
                    <p class="promo-caption">All Notifications</p>
                </a>
            </div>
        </div>
    </div>
    </body>
</html>

notifications/templates/notifications/notification_detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/index.css' %}"/>
<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
<link rel="stylesheet" href="{% static 'css/gh-pages.materialize.css' %}">
<!DOCTYPE html>
<html lang="en">
<body>
<div>
    <h2>{{ notification_data.notification_name }}</h2>
    <p> Header: {{ notification_data.header }} </p>
    <p> Content: {{ notification_data.content }} </p>
    <p> Image: </p>
    <p></p><img src="{{ notification_data.image_url }}" alt="Notification Image" style="max-width:200; height:auto"></p>
    <p>Scheduled Time: {{ notification_data.send_time }}</p>
    <p>Users: Users with {{ notification_data.user_property }} as {{ notification_data.user_property_values }}</p>
    <p>Sent Status: {{ notification_data.sent_status }}</p>
</div>
</body>
</html>

notifications/templates/notifications/notificationdata_form.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/gh-pages.materialize.css' %}">
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/index.css' %}"/>
</head>
<body>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
<script>
$(document).ready(function() {
    $('select').material_select();
});
</script>
<div class="row">
    <h2 class="header">Schedule a notification</h2><br>
    <form class="col s12" action="{% url 'notifications:create' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">title</i>
                <input id="notifname" type="text" class="validate" name="notification_name">
                <label for="notifname">Notification name</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s4">
                <i class="material-icons prefix">text_format</i>
                <input id="headertxt" type="text" class="validate" name="header" minlength="20" maxlength="150">
                <label for="headertxt">Header</label>
            </div>
            <div class="input-field col s4">
                <i class="material-icons prefix">mode_edit</i>
                <input id="contenttxt" type="text" class="validate" name="content" minlength="20" maxlength="300">
                <label for="contenttxt">Content</label>
            </div>
            <div class="input-field col s4">
                <i class="material-icons prefix">link</i>
                <input id="imgurl" type="text" class="validate" name="image_url">
                <label for="imgurl">Image URL</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">date_range</i>
                <!--<input type="date" class="datepicker" id="sendtime" name="send_time">-->
                <input type="text" id="sendtime" class="validate" name="send_time">
                <label for="sendtime">Scheduled Time (Format: YYYY-MM-DD hh:mm:ss)</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">account_circle</i>
                <select id="userprop" name="user_property">
                    <option value="" disabled selected>Choose a user property</option>
                    <option value="id">ID</option>
                    <option value="user_name">User Name</option>
                    <option value="user_city">User City</option>
                </select>
                <label for="userprop">User Properties</label>
            </div>

        </div>
        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">group</i>
                <textarea id="uservals" class="materialize-textarea" name="user_property_values"></textarea>
                <label for="uservals">User Property Values (One per line)</label>
            </div>
        </div>
        <button class="btn waves-effect waves-light" type="submit">Submit</button>
    </form>
</div>
</body>
</html>

notifications/templates/notifications/user_detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/index.css' %}"/>
<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
<link rel="stylesheet" href="{% static 'css/gh-pages.materialize.css' %}">
<!DOCTYPE html>
<html lang="en">
<body>
<div>
    <h2>{{ user.user_name }}</h2>
    <p> ID: {{ user.id }} </p>
    <p> City: {{ user.user_city }} </p>
    <p> Installed: {{ user.installed }} </p>
</div>
</body>
</html>